/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  GithubIntro as GithubIntro
} from './components/github-intro/github-intro';

declare global {
  interface HTMLGithubIntroElement extends GithubIntro, HTMLStencilElement {
  }
  var HTMLGithubIntroElement: {
    prototype: HTMLGithubIntroElement;
    new (): HTMLGithubIntroElement;
  };
  interface HTMLElementTagNameMap {
    "github-intro": HTMLGithubIntroElement;
  }
  interface ElementTagNameMap {
    "github-intro": HTMLGithubIntroElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "github-intro": JSXElements.GithubIntroAttributes;
    }
  }
  namespace JSXElements {
    export interface GithubIntroAttributes extends HTMLAttributes {
      userid?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
